#include "plugin.hpp"

#include <qtsymbolmacros.h>

// Symbol name is generated by Qt from the module URI, so it can't follow our naming style.
// NOLINTNEXTLINE(readability-identifier-naming)
QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Caelestia)

CaelestiaPlugin::CaelestiaPlugin(QObject* parent)
    : QQmlEngineExtensionPlugin(parent) {
    QT_KEEP_SYMBOL(qml_register_types_Caelestia);
}

void CaelestiaPlugin::initializeEngine(QQmlEngine* engine, const char* uri) {
    QQmlEngineExtensionPlugin::initializeEngine(engine, uri);
    m_translations.load(engine);
}
