#pragma once

#include <qqmlextensionplugin.h>

#include "translationloader.hpp"

// Custom QML plugin entry point for the Caelestia module.
//
// Replaces the CMake-autogenerated plugin source (NO_GENERATE_PLUGIN_SOURCE)
// so we can override initializeEngine() and install translations at startup.
class CaelestiaPlugin : public QQmlEngineExtensionPlugin {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    explicit CaelestiaPlugin(QObject* parent = nullptr);

    void initializeEngine(QQmlEngine* engine, const char* uri) override;

private:
    caelestia::TranslationLoader m_translations;
};
