// Custom QML plugin entry point for the Caelestia module.
//
// Replaces the CMake-autogenerated plugin source (NO_GENERATE_PLUGIN_SOURCE)
// so we can override initializeEngine() and install translations at startup.

#include "translationloader.hpp"

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>

QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Caelestia)

class CaelestiaPlugin : public QQmlEngineExtensionPlugin {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    CaelestiaPlugin(QObject* parent = nullptr)
        : QQmlEngineExtensionPlugin(parent) {
        QT_KEEP_SYMBOL(qml_register_types_Caelestia);
    }

    void initializeEngine(QQmlEngine* engine, const char* uri) override {
        QQmlEngineExtensionPlugin::initializeEngine(engine, uri);
        m_translations.load(engine);
    }

private:
    caelestia::TranslationLoader m_translations;
};

#include "plugin.moc"
